export const DEMO_EXPERTS = [
  {
    id: '22222222-0000-0000-0000-000000000001',
    username: 'rafiqul_islam',
    full_name: 'Rafiqul Islam',
    avatar_url: 'https://ui-avatars.com/api/?name=Rafiqul+Islam&background=1a56db&color=fff&size=200&bold=true',
    tagline: 'Fiverr Top Rated Seller | ৳৫ লক্ষ+ আয়ের অভিজ্ঞতা',
    bio: 'আমি ৭ বছর ধরে Fiverr-এ কাজ করছি এবং ১,২০০+ সফল প্রজেক্ট সম্পন্ন করেছি। গ্রাফিক ডিজাইন, লোগো, এবং ব্র্যান্ড আইডেন্টিটিতে বিশেষজ্ঞ। আমার সাথে সেশনে আপনি শিখবেন কীভাবে প্রথম অর্ডার পাবেন, প্রোফাইল অপ্টিমাইজ করবেন এবং আন্তর্জাতিক ক্লায়েন্টের সাথে যোগাযোগ করবেন।',
    category: 'freelancing',
    languages: ['Bengali', 'English'],
    avg_rating: 4.92,
    total_reviews: 198,
    total_sessions: 245,
    response_rate: 98,
    is_online: true,
    verification_status: 'approved',
    min_price: 800,
    created_at: '2023-01-15T00:00:00Z',
    skills: ['Fiverr Profile Optimization', 'গ্রাফিক ডিজাইন', 'Logo Design', 'Client Communication', 'Proposal Writing', 'Pricing Strategy'],
    packages: [
      { id: 'pkg-001-1', title: 'Fiverr প্রোফাইল রিভিউ', description: 'আপনার Fiverr প্রোফাইল, গিগ ট্যাগ ও প্রাইসিং বিশ্লেষণ করে উন্নতির পরামর্শ দেব।', duration_minutes: 20, price_bdt: 800, session_type: ['video'], is_active: true },
      { id: 'pkg-001-2', title: 'ফ্রিল্যান্সিং রোডম্যাপ সেশন', description: 'শূন্য থেকে শুরু করে প্রথম অর্ডার পাওয়া পর্যন্ত সম্পূর্ণ গাইড।', duration_minutes: 40, price_bdt: 1800, session_type: ['video', 'voice'], is_active: true },
    ],
    reviews: [
      { id: 'rv-001-1', rating: 5, comment: 'অসাধারণ পরামর্শ! Fiverr প্রোফাইল অপ্টিমাইজেশনের পর আমার অর্ডার ৩ গুণ বেড়ে গেছে।', reviewer_name: 'Karim Uddin', created_at: '2024-03-10T00:00:00Z' },
      { id: 'rv-001-2', rating: 5, comment: 'খুব সহজভাবে সব বুঝিয়ে দিলেন। মাত্র ২০ মিনিটে অনেক কিছু শিখলাম।', reviewer_name: 'Mou Akter', created_at: '2024-02-20T00:00:00Z' },
      { id: 'rv-001-3', rating: 4, comment: 'ভালো পরামর্শ পেয়েছি। ধন্যবাদ।', reviewer_name: 'Jahid Hasan', created_at: '2024-01-15T00:00:00Z' },
    ],
  },
  {
    id: '22222222-0000-0000-0000-000000000002',
    username: 'nusrat_jahan',
    full_name: 'Nusrat Jahan',
    avatar_url: 'https://ui-avatars.com/api/?name=Nusrat+Jahan&background=0e9f6e&color=fff&size=200&bold=true',
    tagline: 'IELTS 8.5 | কানাডা পিআর ধারক | Study Abroad গাইড',
    bio: 'আমি ২০১৯ সালে IELTS-এ ৮.৫ স্কোর করে কানাডার University of Toronto-তে স্কলারশিপ পাই। বর্তমানে কানাডা পিআর ধারক। আমার কাছ থেকে IELTS Speaking ও Writing টিপস, SOP লেখার কৌশল এবং স্কলারশিপ আবেদনের সম্পূর্ণ গাইড পাবেন।',
    category: 'study-abroad',
    languages: ['Bengali', 'English'],
    avg_rating: 4.87,
    total_reviews: 156,
    total_sessions: 183,
    response_rate: 96,
    is_online: false,
    verification_status: 'approved',
    min_price: 600,
    created_at: '2023-03-20T00:00:00Z',
    skills: ['IELTS Speaking', 'IELTS Writing', 'SOP Writing', 'Canada PR', 'Scholarship Application', 'University Selection'],
    packages: [
      { id: 'pkg-002-1', title: 'IELTS Speaking মক টেস্ট', description: 'রিয়েল পরীক্ষার মতো Speaking মক টেস্ট + বিস্তারিত ফিডব্যাক।', duration_minutes: 20, price_bdt: 600, session_type: ['video'], is_active: true },
      { id: 'pkg-002-2', title: 'স্কলারশিপ আবেদন গাইড', description: 'SOP লেখা, রেফারেন্স লেটার এবং বিশ্ববিদ্যালয় বাছাই নিয়ে বিস্তারিত আলোচনা।', duration_minutes: 40, price_bdt: 1400, session_type: ['video'], is_active: true },
    ],
    reviews: [
      { id: 'rv-002-1', rating: 5, comment: 'Nusrat আপার IELTS টিপসগুলো সত্যিই কাজে লেগেছে। আমার Speaking ব্যান্ড ৬.৫ থেকে ৭.৫ হয়েছে।', reviewer_name: 'Tasnim Begum', created_at: '2024-04-01T00:00:00Z' },
      { id: 'rv-002-2', rating: 5, comment: 'কানাডা আবেদনের পুরো প্রক্রিয়া খুব ভালোভাবে বুঝিয়ে দিলেন।', reviewer_name: 'Riaz Ahmed', created_at: '2024-03-15T00:00:00Z' },
    ],
  },
  {
    id: '22222222-0000-0000-0000-000000000003',
    username: 'tanvir_ahmed',
    full_name: 'Tanvir Ahmed',
    avatar_url: 'https://ui-avatars.com/api/?name=Tanvir+Ahmed&background=7e3af2&color=fff&size=200&bold=true',
    tagline: 'Senior SWE @ FAANG | LeetCode Top 5% | BUET CSE',
    bio: 'BUET CSE থেকে পাশ করে বর্তমানে একটি শীর্ষ মার্কিন টেক কোম্পানিতে Senior Software Engineer হিসেবে কর্মরত। আমি ৩০০+ জনকে সফটওয়্যার ক্যারিয়ারে সাহায্য করেছি — রোডম্যাপ তৈরি থেকে শুরু করে FAANG ইন্টারভিউ প্রস্তুতি পর্যন্ত। LeetCode-এ ২,০০০+ প্রবলেম সমাধান করেছি।',
    category: 'software-career',
    languages: ['Bengali', 'English'],
    avg_rating: 4.95,
    total_reviews: 267,
    total_sessions: 312,
    response_rate: 99,
    is_online: true,
    verification_status: 'approved',
    min_price: 1000,
    created_at: '2022-11-01T00:00:00Z',
    skills: ['Data Structures & Algorithms', 'System Design', 'LeetCode Strategy', 'FAANG Interview Prep', 'Career Roadmap', 'Resume Review', 'Mock Interview'],
    packages: [
      { id: 'pkg-003-1', title: 'LeetCode স্ট্র্যাটেজি সেশন', description: 'কোন টপিক কোন ক্রমে করবেন, সময় বাঁচানোর কৌশল এবং প্যাটার্ন চেনার উপায়।', duration_minutes: 20, price_bdt: 1000, session_type: ['video'], is_active: true },
      { id: 'pkg-003-2', title: 'ক্যারিয়ার রোডম্যাপ রিভিউ', description: 'আপনার বর্তমান অবস্থান মূল্যায়ন করে ৬ মাসের অ্যাকশন প্ল্যান তৈরি।', duration_minutes: 30, price_bdt: 1500, session_type: ['video'], is_active: true },
      { id: 'pkg-003-3', title: 'FAANG ইন্টারভিউ প্রস্তুতি', description: 'System Design + Coding + Behavioral — তিনটি রাউন্ডের জন্য সম্পূর্ণ প্রস্তুতি।', duration_minutes: 40, price_bdt: 2500, session_type: ['video', 'voice'], is_active: true },
    ],
    reviews: [
      { id: 'rv-003-1', rating: 5, comment: 'Tanvir ভাইয়ের System Design ক্লাসটা mind-blowing ছিল। Google-এ ইন্টারভিউ দিয়ে পাস করেছি!', reviewer_name: 'Shakil Islam', created_at: '2024-05-01T00:00:00Z' },
      { id: 'rv-003-2', rating: 5, comment: 'LeetCode কৌশল এত সহজে বুঝিনি আগে। এখন আমি প্রতিদিন ২টা করে সমস্যা সমাধান করতে পারছি।', reviewer_name: 'Priya Das', created_at: '2024-04-10T00:00:00Z' },
      { id: 'rv-003-3', rating: 5, comment: 'ক্যারিয়ার রোডম্যাপ সেশনটা আমার জীবন পরিবর্তন করে দিয়েছে।', reviewer_name: 'Rasel Mahmud', created_at: '2024-03-22T00:00:00Z' },
    ],
  },
  {
    id: '22222222-0000-0000-0000-000000000004',
    username: 'sumaiya_khatun',
    full_name: 'Sumaiya Khatun',
    avatar_url: 'https://ui-avatars.com/api/?name=Sumaiya+Khatun&background=e3a008&color=fff&size=200&bold=true',
    tagline: '৩৭তম BCS (পররাষ্ট্র ক্যাডার) | প্রিলি থেকে ভাইভা গাইড',
    bio: '৩৭তম BCS-এ পররাষ্ট্র ক্যাডারে উত্তীর্ণ হয়ে বর্তমানে সরকারি চাকরিতে আছি। আমার কাছে BCS প্রিলিমিনারি কৌশল, রিটেন প্রস্তুতি এবং ভাইভা গাইডেন্স পাবেন। বিশেষত বাংলাদেশ বিষয়াবলী এবং আন্তর্জাতিক বিষয়াবলীতে আমি বিশেষজ্ঞ।',
    category: 'bcs-govt-jobs',
    languages: ['Bengali'],
    avg_rating: 4.78,
    total_reviews: 82,
    total_sessions: 97,
    response_rate: 94,
    is_online: false,
    verification_status: 'approved',
    min_price: 500,
    created_at: '2023-06-10T00:00:00Z',
    skills: ['BCS Preliminary', 'BCS Written', 'বাংলাদেশ বিষয়াবলী', 'আন্তর্জাতিক বিষয়াবলী', 'Study Planning'],
    packages: [
      { id: 'pkg-004-1', title: 'BCS প্রিলি কৌশল', description: 'সিলেবাস বিশ্লেষণ, গুরুত্বপূর্ণ টপিক এবং সময় ব্যবস্থাপনা নিয়ে আলোচনা।', duration_minutes: 30, price_bdt: 500, session_type: ['video', 'voice'], is_active: true },
      { id: 'pkg-004-2', title: 'BCS ভাইভা প্র্যাকটিস', description: 'মক ভাইভা সেশন — ভাইভা বোর্ডের সম্ভাব্য প্রশ্নোত্তর অনুশীলন।', duration_minutes: 40, price_bdt: 1200, session_type: ['video'], is_active: true },
    ],
    reviews: [
      { id: 'rv-004-1', rating: 5, comment: 'Sumaiya আপার BCS গাইডেন্সে প্রিলিতে পাস করেছি। অনেক ধন্যবাদ!', reviewer_name: 'Habib Rahman', created_at: '2024-02-14T00:00:00Z' },
      { id: 'rv-004-2', rating: 4, comment: 'আন্তর্জাতিক বিষয়াবলীর টিপসগুলো খুব কাজে লেগেছে।', reviewer_name: 'Nasrin Sultana', created_at: '2024-01-30T00:00:00Z' },
    ],
  },
  {
    id: '22222222-0000-0000-0000-000000000005',
    username: 'arif_hossain',
    full_name: 'Arif Hossain',
    avatar_url: 'https://ui-avatars.com/api/?name=Arif+Hossain&background=e74694&color=fff&size=200&bold=true',
    tagline: 'Serial Entrepreneur | ৩টি সফল স্টার্টআপ | VC ফান্ডেড',
    bio: 'আমি গত ১০ বছরে ৩টি স্টার্টআপ প্রতিষ্ঠা করেছি, যার মধ্যে ২টি সফলভাবে বিক্রি করেছি। বর্তমান উদ্যোগটি VC থেকে $২ মিলিয়ন ফান্ডিং পেয়েছে। বিজনেস প্ল্যান, মার্কেট রিসার্চ, ফান্ডিং স্ট্র্যাটেজি এবং টিম ম্যানেজমেন্টে গাইডেন্স দিতে পারি।',
    category: 'business',
    languages: ['Bengali', 'English'],
    avg_rating: 4.83,
    total_reviews: 129,
    total_sessions: 156,
    response_rate: 97,
    is_online: true,
    verification_status: 'approved',
    min_price: 1200,
    created_at: '2023-02-05T00:00:00Z',
    skills: ['Business Plan', 'Startup Strategy', 'VC Fundraising', 'Market Research', 'Digital Marketing', 'Team Building'],
    packages: [
      { id: 'pkg-005-1', title: 'বিজনেস আইডিয়া ভ্যালিডেশন', description: 'আপনার বিজনেস আইডিয়া কতটা বাস্তবসম্মত তা মূল্যায়ন করব এবং উন্নতির পরামর্শ দেব।', duration_minutes: 20, price_bdt: 1200, session_type: ['video'], is_active: true },
      { id: 'pkg-005-2', title: 'স্টার্টআপ স্ট্র্যাটেজি সেশন', description: 'বিজনেস মডেল, মার্কেটিং প্ল্যান এবং ফান্ডিং রোডম্যাপ নিয়ে গভীর আলোচনা।', duration_minutes: 40, price_bdt: 3000, session_type: ['video', 'voice'], is_active: true },
    ],
    reviews: [
      { id: 'rv-005-1', rating: 5, comment: 'আমার স্টার্টআপ আইডিয়াটা ভ্যালিডেট করতে Arif ভাইয়ের পরামর্শ অমূল্য ছিল।', reviewer_name: 'Tania Islam', created_at: '2024-04-20T00:00:00Z' },
    ],
  },
  {
    id: '22222222-0000-0000-0000-000000000006',
    username: 'fatema_begum',
    full_name: 'Fatema Begum',
    avatar_url: 'https://ui-avatars.com/api/?name=Fatema+Begum&background=1c64f2&color=fff&size=200&bold=true',
    tagline: 'আইনজীবী (বাংলাদেশ সুপ্রিম কোর্ট) | ১৫ বছরের অভিজ্ঞতা',
    bio: 'বাংলাদেশ সুপ্রিম কোর্টের এনরোলড আইনজীবী হিসেবে ১৫ বছর ধরে চুক্তি আইন, ব্যবসায়িক আইন এবং পারিবারিক আইনে প্র্যাকটিস করছি। আমার সেশনে আপনি ব্যবসায়িক চুক্তি পর্যালোচনা, বিরোধ নিষ্পত্তি পরামর্শ এবং আইনি ঝুঁকি মূল্যায়ন করতে পারবেন।',
    category: 'legal',
    languages: ['Bengali', 'English'],
    avg_rating: 4.71,
    total_reviews: 51,
    total_sessions: 64,
    response_rate: 92,
    is_online: false,
    verification_status: 'approved',
    min_price: 800,
    created_at: '2023-05-18T00:00:00Z',
    skills: ['Contract Review', 'Business Law', 'Civil Law', 'Family Law', 'Dispute Resolution'],
    packages: [
      { id: 'pkg-006-1', title: 'চুক্তি পর্যালোচনা পরামর্শ', description: 'আপনার ব্যবসায়িক চুক্তির আইনি ঝুঁকি মূল্যায়ন ও পরামর্শ।', duration_minutes: 30, price_bdt: 800, session_type: ['video', 'voice'], is_active: true },
      { id: 'pkg-006-2', title: 'আইনি পরামর্শ সেশন', description: 'আপনার নির্দিষ্ট আইনি সমস্যা নিয়ে বিস্তারিত আলোচনা ও সমাধানের পথ।', duration_minutes: 40, price_bdt: 2000, session_type: ['video'], is_active: true },
    ],
    reviews: [
      { id: 'rv-006-1', rating: 5, comment: 'ব্যবসায়িক চুক্তির জটিলতা সহজে বুঝিয়ে দিলেন। অনেক উপকার হয়েছে।', reviewer_name: 'Faruk Hossain', created_at: '2024-03-05T00:00:00Z' },
    ],
  },
  {
    id: '22222222-0000-0000-0000-000000000007',
    username: 'sabbir_rahman',
    full_name: 'Sabbir Rahman',
    avatar_url: 'https://ui-avatars.com/api/?name=Sabbir+Rahman&background=057a55&color=fff&size=200&bold=true',
    tagline: 'Upwork Top Rated Plus | ওয়েব ডেভেলপমেন্টে $৫০k+ আয়',
    bio: 'Upwork-এ Top Rated Plus ব্যাজ ধারী ওয়েব ডেভেলপার। React, Node.js এবং WordPress-এ বিশেষজ্ঞ। আমার সাথে সেশনে শিখবেন কীভাবে Upwork প্রোফাইল তৈরি করতে হয়, প্রপোজাল লিখতে হয় এবং বিদেশী ক্লায়েন্টের সাথে দীর্ঘমেয়াদী সম্পর্ক তৈরি করতে হয়।',
    category: 'freelancing',
    languages: ['Bengali', 'English'],
    avg_rating: 4.65,
    total_reviews: 61,
    total_sessions: 78,
    response_rate: 91,
    is_online: true,
    verification_status: 'approved',
    min_price: 500,
    created_at: '2023-07-22T00:00:00Z',
    skills: ['Upwork Profile', 'React.js', 'Node.js', 'WordPress', 'Proposal Writing', 'Client Retention'],
    packages: [
      { id: 'pkg-007-1', title: 'Upwork প্রোফাইল অপ্টিমাইজেশন', description: 'প্রোফাইল, পোর্টফোলিও এবং প্রথম প্রপোজাল লেখার গাইড।', duration_minutes: 20, price_bdt: 500, session_type: ['video'], is_active: true },
      { id: 'pkg-007-2', title: 'ওয়েব ডেভেলপমেন্ট ক্যারিয়ার গাইড', description: 'স্কিল রোডম্যাপ, ফ্রিল্যান্স vs চাকরি এবং প্রথম ক্লায়েন্ট পাওয়ার কৌশল।', duration_minutes: 30, price_bdt: 1000, session_type: ['video', 'voice'], is_active: true },
    ],
    reviews: [
      { id: 'rv-007-1', rating: 5, comment: 'Sabbir ভাইয়ের Upwork টিপসে প্রথম সপ্তাহেই ২টা কাজ পেয়েছি!', reviewer_name: 'Limon Ahmed', created_at: '2024-02-28T00:00:00Z' },
    ],
  },
  {
    id: '22222222-0000-0000-0000-000000000008',
    username: 'mehrin_akter',
    full_name: 'Mehrin Akter',
    avatar_url: 'https://ui-avatars.com/api/?name=Mehrin+Akter&background=c81e1e&color=fff&size=200&bold=true',
    tagline: 'অস্ট্রেলিয়া PR | Monash University গ্র্যাজুয়েট | ভিসা গাইড',
    bio: 'অস্ট্রেলিয়ার Monash University থেকে Masters সম্পন্ন করে স্থায়ী বাসিন্দা। Student Visa থেকে PR পর্যন্ত পুরো প্রক্রিয়া নিজে পার করেছি। IELTS Academic, অস্ট্রেলিয়া/কানাডা ভিসা আবেদন এবং বৃত্তির সুযোগ নিয়ে বিস্তারিত পরামর্শ দিতে পারি।',
    category: 'study-abroad',
    languages: ['Bengali', 'English'],
    avg_rating: 4.80,
    total_reviews: 118,
    total_sessions: 142,
    response_rate: 95,
    is_online: false,
    verification_status: 'approved',
    min_price: 700,
    created_at: '2023-04-12T00:00:00Z',
    skills: ['Australia PR', 'Student Visa', 'IELTS Academic', 'Scholarship', 'University Shortlisting'],
    packages: [
      { id: 'pkg-008-1', title: 'অস্ট্রেলিয়া স্টুডেন্ট ভিসা গাইড', description: 'ভিসা আবেদন প্রক্রিয়া, প্রয়োজনীয় কাগজপত্র এবং সাধারণ ভুল এড়ানোর উপায়।', duration_minutes: 30, price_bdt: 700, session_type: ['video'], is_active: true },
      { id: 'pkg-008-2', title: 'স্টাডি অ্যাব্রোড সম্পূর্ণ প্যাকেজ', description: 'বিশ্ববিদ্যালয় বাছাই থেকে ভিসা পাওয়া পর্যন্ত সম্পূর্ণ গাইড।', duration_minutes: 40, price_bdt: 1600, session_type: ['video'], is_active: true },
    ],
    reviews: [
      { id: 'rv-008-1', rating: 5, comment: 'Mehrin আপার গাইডেন্সে অস্ট্রেলিয়া ভিসা পেয়েছি। স্বপ্ন পূরণ হলো!', reviewer_name: 'Sadia Islam', created_at: '2024-04-15T00:00:00Z' },
      { id: 'rv-008-2', rating: 5, comment: 'IELTS Academic স্কোর বাড়াতে অনেক সাহায্য করেছেন।', reviewer_name: 'Kamrul Hasan', created_at: '2024-03-01T00:00:00Z' },
    ],
  },
  {
    id: '22222222-0000-0000-0000-000000000009',
    username: 'imran_khan',
    full_name: 'Imran Khan',
    avatar_url: 'https://ui-avatars.com/api/?name=Imran+Khan&background=6875f5&color=fff&size=200&bold=true',
    tagline: 'Full Stack Developer | React & Python বিশেষজ্ঞ | ৫+ বছর',
    bio: 'ঢাকার একটি লিডিং টেক কোম্পানিতে Lead Developer হিসেবে কাজ করছি। React, Python/Django, PostgreSQL এবং AWS-এ দক্ষ। জুনিয়র ডেভেলপারদের রোডম্যাপ তৈরি, পোর্টফোলিও রিভিউ এবং লোকাল ও রিমোট জব ইন্টারভিউ প্রস্তুতিতে সাহায্য করি।',
    category: 'software-career',
    languages: ['Bengali', 'English'],
    avg_rating: 4.88,
    total_reviews: 172,
    total_sessions: 201,
    response_rate: 97,
    is_online: true,
    verification_status: 'approved',
    min_price: 900,
    created_at: '2023-01-30T00:00:00Z',
    skills: ['React.js', 'Python / Django', 'PostgreSQL', 'AWS', 'Portfolio Review', 'Job Interview Prep'],
    packages: [
      { id: 'pkg-009-1', title: 'প্রোগ্রামিং রোডম্যাপ', description: 'আপনার দক্ষতা মূল্যায়ন করে পরবর্তী ৩–৬ মাসের শেখার পরিকল্পনা তৈরি।', duration_minutes: 20, price_bdt: 900, session_type: ['video', 'voice'], is_active: true },
      { id: 'pkg-009-2', title: 'পোর্টফোলিও ও রেজিউমি রিভিউ', description: 'GitHub প্রোজেক্ট, পোর্টফোলিও সাইট এবং রেজিউমি পর্যালোচনা ও উন্নতির পরামর্শ।', duration_minutes: 30, price_bdt: 1400, session_type: ['video'], is_active: true },
      { id: 'pkg-009-3', title: 'জব ইন্টারভিউ প্র্যাকটিস', description: 'টেকনিক্যাল ও HR ইন্টারভিউ মক সেশন সহ বিস্তারিত ফিডব্যাক।', duration_minutes: 40, price_bdt: 2200, session_type: ['video'], is_active: true },
    ],
    reviews: [
      { id: 'rv-009-1', rating: 5, comment: 'React রোডম্যাপ সেশনের পর আমার শেখার গতি দ্বিগুণ হয়েছে।', reviewer_name: 'Arman Ali', created_at: '2024-05-10T00:00:00Z' },
      { id: 'rv-009-2', rating: 5, comment: 'Portfolio রিভিউ সেশনে অনেক মূল্যবান feedback পেয়েছি।', reviewer_name: 'Sujon Mia', created_at: '2024-04-25T00:00:00Z' },
    ],
  },
  {
    id: '22222222-0000-0000-0000-000000000010',
    username: 'roksana_parvin',
    full_name: 'Roksana Parvin',
    avatar_url: 'https://ui-avatars.com/api/?name=Roksana+Parvin&background=0694a2&color=fff&size=200&bold=true',
    tagline: '৪১তম BCS (প্রশাসন ক্যাডার) | ভাইভা বোর্ড অভিজ্ঞতা সম্পন্ন',
    bio: '৪১তম BCS-এ প্রশাসন ক্যাডারে উত্তীর্ণ। ৪র্থ প্রচেষ্টায় সফল হয়েছি — তাই জানি কোথায় ভুল হয় এবং কীভাবে ঘুরে দাঁড়াতে হয়। BCS ভাইভা বোর্ডের প্রশ্নের ধরন, মানসিক প্রস্তুতি এবং সময় ব্যবস্থাপনায় আমার বিশেষ দক্ষতা আছে।',
    category: 'bcs-govt-jobs',
    languages: ['Bengali'],
    avg_rating: 4.91,
    total_reviews: 241,
    total_sessions: 289,
    response_rate: 99,
    is_online: false,
    verification_status: 'approved',
    min_price: 600,
    created_at: '2022-12-20T00:00:00Z',
    skills: ['BCS Viva', 'BCS Preliminary', 'সাধারণ জ্ঞান', 'মানসিক প্রস্তুতি', 'Time Management', 'Mock Viva'],
    packages: [
      { id: 'pkg-010-1', title: 'BCS ভাইভা মক সেশন', description: 'বাস্তব ভাইভা বোর্ডের মতো প্র্যাকটিস — প্রশ্নোত্তর ও ফিডব্যাক।', duration_minutes: 30, price_bdt: 600, session_type: ['video'], is_active: true },
      { id: 'pkg-010-2', title: 'BCS সম্পূর্ণ কৌশল সেশন', description: 'প্রিলি থেকে ভাইভা — সম্পূর্ণ প্রস্তুতির রোডম্যাপ এবং মানসিক প্রস্তুতি।', duration_minutes: 40, price_bdt: 1500, session_type: ['video', 'voice'], is_active: true },
    ],
    reviews: [
      { id: 'rv-010-1', rating: 5, comment: 'Roksana আপার মক ভাইভা সেশন আমাকে আত্মবিশ্বাসী করে তুলেছে। BCS-এ পাস করেছি!', reviewer_name: 'Bellal Hossain', created_at: '2024-05-20T00:00:00Z' },
      { id: 'rv-010-2', rating: 5, comment: '৪র্থ প্রচেষ্টার গল্প শুনে অনুপ্রাণিত হয়েছি। সেরা মেন্টর।', reviewer_name: 'Sharmin Akter', created_at: '2024-04-30T00:00:00Z' },
      { id: 'rv-010-3', rating: 5, comment: 'ভাইভা বোর্ডের প্রশ্ন কীভাবে হ্যান্ডেল করতে হয় সেটা শিখিয়ে দিলেন।', reviewer_name: 'Rubel Ahmed', created_at: '2024-04-12T00:00:00Z' },
    ],
  },
];

export const DEMO_EXPERT_MAP = Object.fromEntries(
  DEMO_EXPERTS.map((e) => [e.username, e])
);

export const DEMO_EXPERT_ID_MAP = Object.fromEntries(
  DEMO_EXPERTS.map((e) => [e.id, e])
);
